version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and run the development environment container.
          command: make ready
      - run:
          name: Run the CI suite.
          command: make ci
      - run:
          name: Build and run some example programs.
          command: |
